config/routes.rb
Rails.application.routes.draw do
  resources :requests, except: [:edit] do
    resources :users, only: [:new, :create,:update]
  end
  resources :users, except: [:new,:create] do
    get 'refuse_page'
    post 'refuse', to: 'users#refuse'
  end
  # resources :articles do
  #   resources :comments, only: [:index, :new, :create]
  # end
  # resources :comments, only: [:show, :edit, :update, :destroy]
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  # after_update :set_state
  has_many :users, dependent: :destroy
  # accepts_nested_attributes_for :users
  # attr_accessor :user_data
  mount_uploader :attachment, AttachmentUploader
  validates :docname, presence: true
  validates :attachment, presence: true
  
  private
  
  def set_state
    Request.all.each do |request|
      if request.users.length == 0
        request.state = "Pendente"
        return request.save
      end
      request.users.each do |user|
        if user.signed.nil?
          request.state = "Pendente"
        elsif !user.signed
          request.state = "Reprovada"  
        end
      end
      request.state = "Aprovada"
      request.save
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # after_update :set_state
  belongs_to :request
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true, format: {with: EMAIL_REGEX}
  
  private

  def set_state
    Request.all.each do |request|
      if request.users.length == 0
        request.state = "Pendente"
        return request.save
      end
      request.users.each do |user|
        if user.signed.nil?
          request.state = "Pendente"
        elsif !user.signed
          request.state = "Reprovada"  
        end
      end
      request.state = "Aprovada"
      request.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
  def about
    
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  

  def index
    @request = Request.all
    update_state()
    # set_state(@request)
  end
  
  def new
    @request = Request.new
    # @request.users = Request.new
    
  end
  
  def create
    @request = Request.new(request_params)
    @request.state = "Pendente"
    if @request.save
      redirect_to request_path(@request), notice: "O documento foi enviado."
    else
      render 'new'
    end
  end

  def show
    @request = Request.find(params[:id])
  end
  
  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to requests_path, notice: "A solicitação foi deletada."
  end

  private
  
  def request_params
    params.require(:request).permit(:docname, :attachment)
    
  end

  def update_state
    state_string = nil
    request = Request.all
    request.each do |r|
      r.users.each do |user|
        if user.signed.nil?
          state_string = "Pendente"
        elsif user.signed == false
          state_string = "Reprovada"  
        else
          state_string = "Aprovada"
        end
      end
      r.update(:state => "#{state_string}")
    end
  end
 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    
  end
  def create
    @request = Request.find(params[:request_id])
    @user = @request.users.create(user_params)
    if !@user.id.nil?
      UserMailer.notify_email(@user).deliver_later
    end
    redirect_to request_path(@request)
  end

  def update
    @user = User.find(params[:id])
    @request = Request.find(@user.request_id)
    @user.signed = true
    if @user.update(user_signature_params)
      redirect_to request_path(@user.request_id)
    end
  end

  def edit
    # @request = Request.find(params[:request_id])
    @user = User.find(params[:id])
  end

  def refuse_page
    @user = User.find(params[:user_id])
  end
      #Não funcionam
  def refuse
    @user = User.find(params[:user_id])
    @user.reason = params.require(:user).permit(:reason)
    @user.update(@user.signed => false)
    # redirect_to request_path(@user.request_id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
  def user_signature_params
    params.require(:user).permit(:signature)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "DocSigner", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Solicitações", requests_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Nova Solicitação", new_request_path, class: "nav-link" %>
      </li>
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocSigner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
  </head>

  <body class="d-flex flex-column h-100">
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center vertical-center">
    <h1 class="display-1 mt-5 ">DocSigner</h1>
    <p class="lead">Um assinador virtual de documentos, criado para você</p>
    
  </div>
</div>

app/views/requests/index.html.erb
<h1>Solicitações de Assinatura</h1>

<% if !flash[:notice].blank? %>
  <div>
    <%=flash[:notice] %>
  </div>
<% end %>
 
<%= link_to "Nova Solicitação de Assinatura", new_request_path, class:"btn btn-primary" %>
<br><br>
<div class="table-responsive">
  <table class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Estado</th>
        <th scope="col">Data e Hora</th>
        <th scope="col" colspan="2" class="text-center">Ações</th>
      </tr>
    </thead>
    <!-- inserir embed ruby @request.each do -->
    <tbody>
      <% @request.each do |request| %>
      <tr>
        <td><%= request.docname %></td>
        <td><%= request.state %></td>
        <td><%= request.created_at.to_s(:request) %></td>
        <td class="text-center" id="actions"><%= link_to 'Mostrar', request_path(request), class:"btn btn-outline-info" %>
                                <%= link_to 'Cancelar', request_path(request), class:"btn btn-outline-danger",
                method: :delete,
                data: { confirm: 'Realmente deseja excluir?'}%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/requests/new.html.erb
<h1>Criar nova solicitação</h1>

<% if !@request.errors.empty? %>
<div class="alert alert-danger col-5 alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">Algo aconteceu!</h4>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>


<div>
  <%= form_for @request, html: { multipart: true } do |f| %>
    <%= f.label :docname, "Nome do documento" %>
    <%= f.text_field :docname , class:"form-control col-5"%>
    <%= f.label :attachment, "Inserir documento" %>
    <%= f.file_field :attachment , class: "form-control col-5"%>
    <%= f.submit "Salvar" ,class:"btn btn-primary"%>
    <%= link_to "Voltar", :back, class: "btn btn-secondary" %>
    <% end %>
</div>

app/views/requests/show.html.erb
<div>
  <h1 class="mb-5">Visualizar Documento</h1>
  <%= link_to "Voltar",requests_path, class: "btn btn-secondary" %>
  <a class="btn btn-primary view-pdf" href=<%= @request.attachment %> >Ver PDF</a>   
  <div class=" mt-5">
    <table class="table table-bordered table-hover ">
      <thead class="thead-light">
        <tr >
          <th scope="col">Signatário</th>
          <th scope="col">E-mail</th>
          <th scope="col" >Assinatura</th>
          <th class="text-center" scope="col" colspan="2" >Ações</th>
        </tr>
      </thead>
      <tbody>
        <%= render @request.users %>
      </tbody>
      <div class="mb-5">
        <h2>Vincular Signatários</h2>
        <%= render 'users/form' %>
      </div>
    </table>
    
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: [@request, @request.users.build ], local:
true) do |form| %>
  <div class="form-row">
    <div class="col-md-6">
      <%= form.label 'Nome' %><br>
      <%= form.text_field :name, class:"form-control" %><br>
    </div>
    <div class="col-md-6">
      <%= form.label 'E-mail' %><br>
      <%= form.text_field :email, class:"form-control" %><br>
    </div>
    <div class="col-md-6">
      <%= form.submit 'Vincular', class:"btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
  <tr >
    <td class="align-middle"><%= user.name %></td>
    <td class="align-middle"><%= user.email %></td> 
    <td class="align-middle" id="signature-table"> 
      <%= image_tag(user.signature, class: "img-thumbnail") if user.signature? %></td>
    <td class="align-middle text-center" id="actions"><%= link_to "Assinar", edit_user_path(user), class:"btn btn-outline-primary" %>
      <%= link_to "Não Assinar" ,user_refuse_page_path(user), class: "btn btn-outline-danger" %></td>
  </tr>

app/views/users/edit.html.erb
<h1>Assinatura</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <div id="signature_field" class="mb-1">
    <%= f.signature_field :signature%>
  </div>
  <button class="btn btn-secondary" type="button" onclick=signatureClear()>Limpar</button>
  <a class="btn btn-info view-pdf" href=<%= Request.find(@user.request_id).attachment %> >Ver PDF</a>   
  <%= f.submit 'Assinar', class:"btn btn-primary"%>
  <% end %>

app/views/users/refuse.html.erb
<h1>Informe o motivo da recusa</h1>
<%= form_with(model: @user, local: true) do |form| %>
<%= form.text_area :reason, class:"form-control"%>
<%= form.submit 'Enviar' %>
<%= link_to 'Voltar', :back %>
<% end %>

app/views/users/refuse_page.html.erb
<h1>Informe o motivo da recusa</h1>
<%= form_with(model: @user, local: true) do |form| %>
<%= form.text_area :reason, class:"form-control"%>
<%= form.submit 'Enviar' %>
<%= link_to 'Voltar', :back %>
<% end %>